-- noinspection SqlNoDataSourceInspectionForFile
CREATE TABLE USERS(
                      USERNAME VARCHAR(128) NOT NULL PRIMARY KEY,
                      PASSWORD VARCHAR(512) NOT NULL,
                      ENABLED BOOLEAN NOT NULL);

CREATE TABLE AUTHORITIES (
                             USERNAME VARCHAR(128) NOT NULL,
                             AUTHORITY VARCHAR(128) NOT NULL);

CREATE UNIQUE INDEX IDX_AUTH_USERNAME ON AUTHORITIES (USERNAME,AUTHORITY);

CREATE TABLE PUBLIC.T_OWNER(
                               ID BIGINT NOT NULL,
                               FIRST_NAME VARCHAR(255) NOT NULL,
                               LAST_NAME VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.T_OWNER ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);

CREATE TABLE PUBLIC.T_VET(
                               ID BIGINT NOT NULL,
                               FIRST_NAME VARCHAR(255) NOT NULL,
                               LAST_NAME VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.T_VET ADD CONSTRAINT PUBLIC.CONSTRAINT_11 PRIMARY KEY(ID);

CREATE TABLE PUBLIC.T_PET(
                             ID BIGINT NOT NULL,
                             NAME VARCHAR(255),
                             BIRTH_DATE DATE,
                             OWNER_ID BIGINT
);
ALTER TABLE PUBLIC.T_PET ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);

ALTER TABLE PUBLIC.T_PET ADD  CONSTRAINT public.CONSTRAINT_3 FOREIGN KEY(OWNER_ID)  REFERENCES PUBLIC.T_OWNER(ID);

CREATE SEQUENCE PUBLIC.PETCLINIC_SEQUENCE START WITH 100;
